import 'tables.dart';
import 'package:drift/drift.dart';

// Generated by drift_dev when running `build_runner build`
// part 'database.g.dart';

@DriftDatabase(tables: [
  User, PubKey, Signature,
  RecommendedAddition, ContestedAddition,
  Product, ProductRecommendation,
  Category, CategoryRecommendation,
  Subcategory, SubcategoryRecommendation,
  ProductType, ProductTypeRecommendation,
  Brand, BrandRecommendation,
  Company, CompanyRecommendation,
  Link, LinkRecommendation,
  Image, ImageRecommendation,
  Interaction, OK, Message, Comment
//, include: {'sql.drift'}
])
class SharedDatabase extends _$MyDatabase {
  SharedDatabase(QueryExecutor e) : super();

  //override
  //int get schemaVersion => 2;
}
