import 'dart:math';
import 'tables.dart';
import 'package:drift/drift.dart';

// Generated by drift_dev when running `build_runner build`
part 'database.g.dart';

@DriftDatabase(tables: [
  User, PubKey, Signature,
  RecommendedAddition,
  Product, ProductRecommendation,
  Category, CategoryRecommendation,
  Subcategory, SubcategoryRecommendation,
  ProductType, ProductTypeRecommendation,
  Link, LinkRecommendation,
  Image, ImageRecommendation,
  Interaction, OK, Message, Comment
//, include: {'sql.drift'}]
)

class SharedDatabase extends _$MyDatabase {
    SharedDatabase(QueryExecutor e): super(e);

  @override
  int get schemaVersion => 2;
}