//import 'src/tables.dart';
import 'package:drift/drift.dart';

// Generated by drift_dev when running `build_runner build`
part 'database.g.dart';

@DriftDatabase(
    /*tables: [
  User, PubKey, Signature,
  RecommendedAddition, ContestedAddition,
  Product, ProductRecommendation,
  Category, CategoryRecommendation,
  Subcategory, SubcategoryRecommendation,
  ProductType, ProductTypeRecommendation,
  Brand, BrandRecommendation,
  Company, CompanyRecommendation,
  Link, LinkRecommendation,
  Image, ImageRecommendation,
  Interaction, OK, Message, Comment],*/
    include: {'src/tables.drift'})
class SharedDatabase extends _$SharedDatabase {
  //SharedDatabase(DatabaseConnection conn) : super.connect(conn);

  SharedDatabase(QueryExecutor e) : super(e);

  //SharedDatabase() : super(_openConnection());

  @override
  int get schemaVersion => 1;
}
